[book]
language = "en"
multilingual = false
src = "src"
title = "Registration Desk"

[build]
create-missing = true
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/ksch-workflows/registration-desk"
edit-url-template = "https://github.com/ksch-workflows/registration-desk/edit/gh-pages/{path}"
site-url = "/registration-desk/"

[output.html.fold]
enable = true
level = 0
