[book]
language = "en"
multilingual = false
src = "src"
title = "Registration Desk"

[build]
create-missing = true
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/ksch-workflows/registration-desk"
edit-url-template = "https://github.com/experimental-software/cheat-sheets/issues/new?title=Foo%3A%20&body={path}"

[output.html.fold]
enable = true
level = 0
