name: registration_desk
description: Web application for the staff working at the registration desk.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  test: ^1.16.5
  get_it: ^7.1.3
  ksch_dart_client:
    path: ../ksch-dart-client
#    git:
#      url: https://github.com/ksch-workflows/ksch_dart_client
#      ref: a85c7f0cb83087d13e207b1331bcf6f64676e995

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  nock: ^1.1.2

flutter:
  uses-material-design: true

dependency_overrides:
  crypto: ^3.0.0
