name: registration_desk
description: Web application for the staff working at the registration desk.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.0
  meta: ^1.7.0
  test: ^1.16.5
  get_it: ^7.1.3
  ksch_dart_client:
    #    path: ../ksch-dart-client
    git:
      url: https://github.com/ksch-workflows/ksch-dart-client
      ref: f40defd5adb641b40916e6660ec7d8032b6a76d7
  loader_overlay: ^2.0.4+3
  dart_jsonwebtoken: ^2.6.2

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  nock:
    git:
      url: https://github.com/cah4a/dart_nock
      ref: 7643ccb71b1340e81d6291028d0a7eae9da45bb3

flutter:
  uses-material-design: true

dependency_overrides:
  crypto: ^3.0.0
