name: Publish WebJar to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - run: ./tool/webjar/publish.sh -v ${GITHUB_REF#refs/*/} -b https://ksch-workflows-306713.ey.r.appspot.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
